/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: repeat.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "repeat.pb-c.h"
void   data__init
                     (Data         *message)
{
  static Data init_value = DATA__INIT;
  *message = init_value;
}
size_t data__get_packed_size
                     (const Data *message)
{
  assert(message->base.descriptor == &data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data__pack
                     (const Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data__pack_to_buffer
                     (const Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Data *
       data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Data *)
     protobuf_c_message_unpack (&data__descriptor,
                                allocator, len, data);
}
void   data__free_unpacked
                     (Data *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_list__init
                     (DataList         *message)
{
  static DataList init_value = DATA_LIST__INIT;
  *message = init_value;
}
size_t data_list__get_packed_size
                     (const DataList *message)
{
  assert(message->base.descriptor == &data_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_list__pack
                     (const DataList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_list__pack_to_buffer
                     (const DataList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataList *
       data_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataList *)
     protobuf_c_message_unpack (&data_list__descriptor,
                                allocator, len, data);
}
void   data_list__free_unpacked
                     (DataList *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &data_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor data__field_descriptors[1] =
{
  {
    "data",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Data, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange data__number_ranges[1 + 1] =
{
  { 10, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Data",
  "Data",
  "Data",
  "",
  sizeof(Data),
  1,
  data__field_descriptors,
  data__field_indices_by_name,
  1,  data__number_ranges,
  (ProtobufCMessageInit) data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_list__field_descriptors[1] =
{
  {
    "data_list",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DataList, n_data_list),
    offsetof(DataList, data_list),
    &data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_list__field_indices_by_name[] = {
  0,   /* field[0] = data_list */
};
static const ProtobufCIntRange data_list__number_ranges[1 + 1] =
{
  { 10, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor data_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataList",
  "DataList",
  "DataList",
  "",
  sizeof(DataList),
  1,
  data_list__field_descriptors,
  data_list__field_indices_by_name,
  1,  data_list__number_ranges,
  (ProtobufCMessageInit) data_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
