# br0
ip link set dev br0 down
ip link set dev br0 up address 02:78:06:c7:b1:4e broadcast ff:ff:ff:ff:ff:ff
ip addr flush dev br0 2>/dev/null
ip route flush dev br0 proto boot 2>/dev/null

# manbr
ip link set dev manbr down
ip link set dev manbr up address 6c:92:bf:13:ff:34 broadcast ff:ff:ff:ff:ff:ff
ip addr flush dev manbr 2>/dev/null
ip -f inet addr add 172.27.167.32/26 scope global label manbr dev manbr
ip route flush dev manbr proto boot 2>/dev/null
ip route add default via 172.27.167.1 dev manbr

# vmlan
ip link set dev vmlan down
ip link set dev vmlan up address 52:65:01:11:ff:f8 broadcast ff:ff:ff:ff:ff:ff
ip addr flush dev vmlan 2>/dev/null
ip -f inet addr add 10.9.255.248/16 scope global label vmlan dev vmlan
ip route flush dev vmlan proto boot 2>/dev/null
ip route add 10.10.0.0/16  scope link dev vmlan
ip route add 10.0.0.0/8  scope link dev vmlan

# global
iptables-restore <<'EOF'
# Generated by iptables-save v1.4.7 on Tue Aug  9 11:48:06 2016
*filter
:INPUT ACCEPT [22505:2134823]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [5356:1855527]
COMMIT
# Completed on Tue Aug  9 11:48:06 2016
EOF
