#!/bin/bash

if [ $# -lt 1 ]
then
	echo "go jumper/devel/p"
	exit 1
fi

if [ $1 = "jumper" ]
then
	exec ssh wenxu@192.168.150.169
elif  [ $1 = "devel" ]
then
	exec ssh -X root@123.59.132.129
elif  [ $1 = "p" ]
then
	exec ssh root@106.75.11.26
elif  [ $1 = "kernel" ]
then
	exec ssh root@106.75.96.146
elif  [ $1 = "p4" ]
then
	exec ssh root@106.75.18.149
else
	echo "parmater should be jumper/devel/p/kernel"
fi


