language: c
compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - OPTS="--disable-ssl"
  - TESTSUITE=1 KERNEL=3.18.1
  - TESTSUITE=1 OPTS="--enable-shared"
  - BUILD_ENV="-m32" OPTS="--disable-ssl"
  - KERNEL=3.17.7 DPDK=1
  - KERNEL=3.17.7 DPDK=1 OPTS="--enable-shared"
  - KERNEL=4.7.2
  - KERNEL=4.4.15
  - KERNEL=4.1.28
  - KERNEL=3.18.37
  - KERNEL=3.14.73
  - KERNEL=3.12.61
  - KERNEL=3.10.102
  - TESTSUITE=1 LIBS=-ljemalloc

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - build@openvswitch.org
